### PR TITLE
Fix expire tag

### LINKED ISSUE #2599: Change expiry to expiration + timeUnit on extend in updateAllocationRequestInternal
Update allocation should use extend allocation to extend it to time unit instead of using --expiry tag from input.

### PR DESCRIPTION
**Pull request by Jayashsatolia403**
A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber:
- gosdk:
- system_test:
- zwalletcli:
- Other: ...

### CODE REVIEW

File: cmd/newallocation.go [hunk 1]
```diff
@@ -151,12 +151,21 @@ var newallocationCmd = &cobra.Command{
 			}
 		}
 
-		var expire time.Duration
-		if expire, err = flags.GetDuration("expire"); err != nil {
-			log.Fatal("invalid 'expire' flag: ", err)
+		config, err := sdk.GetStorageSCConfig()
```
Comment (dabasov) [inline cmd/newallocation.go:154]: we can completely remove this flag for now, and simply hardcode 1 time-unit in smart contract. in the future we can have 1,2,3.. time-units for an allocation when we buy it

**Review by dabasov — CHANGES_REQUESTED** [review]

**Review by dabasov — APPROVED** [review]
lgtm
