### PR TITLE
Fix/download cost calculation

### LINKED ISSUE #196: Issue with download-cost calculation
Download-cost calculation from zbox is used in system-tests.
Currently system-test for read-pool reduction checks for equality of same value before and after download, which itself is an issue that it is passing.

I uploaded zboxcli's `main.go` file which is `142 bytes` in `dev.0chain.net` network with `--data 2` and `--parity 2`. The download-cost returned by zboxcli was `13.613 uZcn`.
Blobber read-prices were:
```
  blobbers:
  - blobber_id:  0a58682c5314fcc160b2f17c3808de126a65ee2d5b0f77adbe0712fe83cb89b1
  - balance:     124.965 mZCN
  - blobber_id:  1717ae320f78e9798a21889b1a91d86c90110e3d1090debcd6c8ee5dc27a96f2
  - balance:     125.007 mZCN
  - blobber_id:  41a6d2c790776c06d6d0b1bb8bff394a9d8c273b4bd700e08db2c771a34b3a47
  - balance:     124.965 mZCN
  - blobber_id:  dfe99b25053106f3edd2517ec3f34ea719b9a7c6fc3ed09aca16050fd0aec515
  - balance:     125.007 mZCN

```

After downloading `main.go` read-pool balance reduced from `500 mZCN` to `499.946 mZCN` which is download-cost is `0.054 mZCN`
Instead `zbox get-download-cost` returned `13.613 uZCN` which is lesser than `0.054 mZCN`.

### PR DESCRIPTION
**Pull request by lpoli**
This PR solves download cost calculation of `zbox get-download-cost` and `zbox get` commands

### CODE REVIEW

File: cmd/getallocation.go [hunk 1]
```diff
@@ -98,6 +70,15 @@ var getallocationCmd = &cobra.Command{
 			return fmt.Sprintf("%s-%s", common.Balance(pr.Min), common.Balance(pr.Max))
 		}
 
+		blockspermarker, err := cmd.Flags().GetInt("blockspermarker")
```
Comment (peterlimg) [inline cmd/getallocation.go]: variable `blockspermarker` -> `blocksPerMarker`

The flag `blockspermarker` -> `blocks-per-marker` if it is a new flag.

File: cmd/getallocation.go [hunk 2]
```diff
@@ -184,36 +156,41 @@ func sizeInGB(size int64) float64 {
...
-func downloadCost(alloc *sdk.Allocation, meta *sdk.ConsolidatedFileMeta) {
-
-	if meta.Type != fileref.FILE {
-		log.Fatal("not a file")
-	}
-
-	var (
-		ps  = perShard(meta.Size, alloc.DataShards, alloc.ParityShards)
-		cps = (ps + fileref.CHUNK_SIZE - 1) / fileref.CHUNK_SIZE
+func calculateDownloadCost(alloc *sdk.Allocation, fileSize int64, blockspermarker int) common.Balance {
```
Comment (peterlimg) [inline cmd/getallocation.go]: blockspermarker -> blocksPerMarker

File: cmd/getallocation.go [hunk 3]
```diff
@@ -413,12 +399,14 @@ func init() {
 	rootCmd.AddCommand(getUploadCostCmd)
 
 	getallocationCmd.PersistentFlags().String("allocation", "", "Allocation ID")
+	getallocationCmd.PersistentFlags().Int("blockspermarker", 10, "blocks signed per Read Marker")
```
Comment (peterlimg) [inline cmd/getallocation.go]: blockspermarker -> blocks-per-marker

File: cmd/getallocation.go [hunk 4]
```diff
@@ -184,36 +156,41 @@ func sizeInGB(size int64) float64 {
...
-		cps = (ps + fileref.CHUNK_SIZE - 1) / fileref.CHUNK_SIZE
+func calculateDownloadCost(alloc *sdk.Allocation, fileSize int64, blockspermarker int) common.Balance {
+	chunkSize := fileref.CHUNK_SIZE
+	dataShards := alloc.DataShards
 
-		size float64        // GB
-		cost common.Balance //
-	)
+	// singleShardSize collection of data-shards
+	singleShardSize := fileref.CHUNK_SIZE * dataShards
```
Comment (peterlimg) [inline cmd/getallocation.go:164]: Shouldn't we include the ParityShards?

**Review by peterlimg — CHANGES_REQUESTED** [review]

File: cmd/getallocation.go (hunk 4 above)
Comment (lpoli) [reply cmd/getallocation.go:164]: No we should not. Because data is divided equally within data-shards regardless of number of parity shards

File: cmd/getallocation.go (hunk 1 above)
Comment (lpoli) [reply cmd/getallocation.go]: @peterlimg Its a new flag for this command but there is `download` command that uses `blockspermarker`. This flag can be used in other tools so to make it consistent with `download`, I followed same pattern

File: cmd/getallocation.go [hunk 5]
```diff
@@ -98,6 +70,15 @@ var getallocationCmd = &cobra.Command{
 			return fmt.Sprintf("%s-%s", common.Balance(pr.Min), common.Balance(pr.Max))
 		}
 
+		blocksPerMarker, err := cmd.Flags().GetInt("blocksPerMarker")
```
Comment (peterlimg) [inline cmd/getallocation.go]: The flag is `blocks-per-maker`

**Review by peterlimg — DISMISSED** [review]

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/download-cost-calculation  |
| gosdk  | staging  |
| zboxcli  | fix/download-cost-calculation  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by Kishan-Dhakan — APPROVED** [review]
Approving as @lpoli asked to merge this branch here: https://0chain.slack.com/archives/C02AV6MKT36/p1648395601349229?thread_ts=1648394208.517439&cid=C02AV6MKT36 and this is blocking other Devs.
